/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AdminRouteImport } from './routes/admin';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AdminIndexRouteImport } from './routes/admin.index';
import { Route as AufgabeTaskIdRouteImport } from './routes/aufgabe.$taskId';
import { Route as AdminKatalogRouteImport } from './routes/admin.katalog';
import { Route as AdminParticipantsIndexRouteImport } from './routes/admin.participants.index';
import { Route as AdminParticipantsParticipantIdRouteImport } from './routes/admin.participants.$participantId';

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any);
const AufgabeTaskIdRoute = AufgabeTaskIdRouteImport.update({
  id: '/aufgabe/$taskId',
  path: '/aufgabe/$taskId',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminKatalogRoute = AdminKatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => AdminRoute,
} as any);
const AdminParticipantsIndexRoute = AdminParticipantsIndexRouteImport.update({
  id: '/participants/',
  path: '/participants/',
  getParentRoute: () => AdminRoute,
} as any);
const AdminParticipantsParticipantIdRoute =
  AdminParticipantsParticipantIdRouteImport.update({
    id: '/participants/$participantId',
    path: '/participants/$participantId',
    getParentRoute: () => AdminRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/admin': typeof AdminRouteWithChildren;
  '/login': typeof LoginRoute;
  '/admin/katalog': typeof AdminKatalogRoute;
  '/aufgabe/$taskId': typeof AufgabeTaskIdRoute;
  '/admin/': typeof AdminIndexRoute;
  '/admin/participants/$participantId': typeof AdminParticipantsParticipantIdRoute;
  '/admin/participants/': typeof AdminParticipantsIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/admin/katalog': typeof AdminKatalogRoute;
  '/aufgabe/$taskId': typeof AufgabeTaskIdRoute;
  '/admin': typeof AdminIndexRoute;
  '/admin/participants/$participantId': typeof AdminParticipantsParticipantIdRoute;
  '/admin/participants': typeof AdminParticipantsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/admin': typeof AdminRouteWithChildren;
  '/login': typeof LoginRoute;
  '/admin/katalog': typeof AdminKatalogRoute;
  '/aufgabe/$taskId': typeof AufgabeTaskIdRoute;
  '/admin/': typeof AdminIndexRoute;
  '/admin/participants/$participantId': typeof AdminParticipantsParticipantIdRoute;
  '/admin/participants/': typeof AdminParticipantsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/katalog'
    | '/aufgabe/$taskId'
    | '/admin/'
    | '/admin/participants/$participantId'
    | '/admin/participants/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/login'
    | '/admin/katalog'
    | '/aufgabe/$taskId'
    | '/admin'
    | '/admin/participants/$participantId'
    | '/admin/participants';
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/katalog'
    | '/aufgabe/$taskId'
    | '/admin/'
    | '/admin/participants/$participantId'
    | '/admin/participants/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminRoute: typeof AdminRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  AufgabeTaskIdRoute: typeof AufgabeTaskIdRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin': {
      id: '/admin';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin/': {
      id: '/admin/';
      path: '/';
      fullPath: '/admin/';
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof AdminRoute;
    };
    '/aufgabe/$taskId': {
      id: '/aufgabe/$taskId';
      path: '/aufgabe/$taskId';
      fullPath: '/aufgabe/$taskId';
      preLoaderRoute: typeof AufgabeTaskIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin/katalog': {
      id: '/admin/katalog';
      path: '/katalog';
      fullPath: '/admin/katalog';
      preLoaderRoute: typeof AdminKatalogRouteImport;
      parentRoute: typeof AdminRoute;
    };
    '/admin/participants/': {
      id: '/admin/participants/';
      path: '/participants';
      fullPath: '/admin/participants/';
      preLoaderRoute: typeof AdminParticipantsIndexRouteImport;
      parentRoute: typeof AdminRoute;
    };
    '/admin/participants/$participantId': {
      id: '/admin/participants/$participantId';
      path: '/participants/$participantId';
      fullPath: '/admin/participants/$participantId';
      preLoaderRoute: typeof AdminParticipantsParticipantIdRouteImport;
      parentRoute: typeof AdminRoute;
    };
  }
}

interface AdminRouteChildren {
  AdminKatalogRoute: typeof AdminKatalogRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
  AdminParticipantsParticipantIdRoute: typeof AdminParticipantsParticipantIdRoute;
  AdminParticipantsIndexRoute: typeof AdminParticipantsIndexRoute;
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminKatalogRoute: AdminKatalogRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminParticipantsParticipantIdRoute: AdminParticipantsParticipantIdRoute,
  AdminParticipantsIndexRoute: AdminParticipantsIndexRoute,
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  AufgabeTaskIdRoute: AufgabeTaskIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
